//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EggplantsActivies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Addresses()
        {
            this.Assets = new HashSet<Assets>();
        }
    
        public int AddressID { get; set; }
        public string HouseNumber { get; set; }
        public string Building { get; set; }
        public string ApartmentNumber { get; set; }
        public int TownID { get; set; }
        public Nullable<int> StreetID { get; set; }
        public int StatusID { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        public virtual Streets Streets { get; set; }
        public virtual Towns Towns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assets> Assets { get; set; }
    }
}
