//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EggplantsActivies
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTransactions
    {
        public int TransactionID { get; set; }
        public int AssetID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int StatusID { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
