//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EggplantsActivies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets
    {
        public int AssetsID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public string Description { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal Cost { get; set; }
        public decimal CurrentValue { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsActive { get; set; }
        public Nullable<decimal> ValueChangePercent { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual AssetType AssetType { get; set; }
        public virtual UserManager UserManager { get; set; }
    }
}
