//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EggplantsActivies
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogs
    {
        public int LogID { get; set; }
        public int UserID { get; set; }
        public string ActionPerformed { get; set; }
        public Nullable<System.DateTime> LogTimestamp { get; set; }
        public int StatusID { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
