//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EggplantsActivies
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuedAssets
    {
        public int IssueID { get; set; }
        public int UserID { get; set; }
        public int AssetID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string AssetCode { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual Users Users { get; set; }
    }
}
