//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EggplantsActivies
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserManager()
        {
            this.Assets = new HashSet<Assets>();
        }
    
        public int UserID { get; set; }
        public string Login { get; set; }
        public string First_Name { get; set; }
        public string Second_Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> PassportID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assets> Assets { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual Role Role { get; set; }
    }
}
