//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EggplantsActivies
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueHistory
    {
        public int HistoryID { get; set; }
        public int AssetID { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
        public Nullable<decimal> Value { get; set; }
        public int StatusID { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
